version: "3.7"
services:
  web:
    # build: .  # baca dari Dockerfile
    container_name: contbaru
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOOLING=true
    # volumes:
    #   - .:/app
    #   - ./:/app
    #   - ./app/node_modules
    stdin_open: true
    tty: true
    restart: always

    # image: nginx:alpine
    # ports:
    #   - 3000:3000
    # volumes:
    #   - ./build:/usr/share/nginx/html
